### ISSUE TITLE
[DEV] Alterar MODEL de usuário para refletir novos atributos

### ISSUE THREAD

**Issue by MarceloTTorres** [MarceloTTorres/fec-web#12]
O Model do usuário deve refletir os atributos do banco de dados

**Comment by vvgarcia** [comment]
O dados da tabela usuário estão vindo corretamente. 
Segue anexos:  
![dadosBanco](https://user-images.githubusercontent.com/55606056/67132361-1bec9000-f1df-11e9-9454-b9a9a742a7da.PNG)
![dadosProjeto](https://user-images.githubusercontent.com/55606056/67132368-21e27100-f1df-11e9-8454-23b45f752c9e.PNG)

@weslleypcampos 
@GuilhermeDomingos 
@FernandoHPereira

**Comment by JeanMaduro** [comment]
@JeanMaduro
